qlover/fe-base-scripts

CHANGELOG.md, package.json
This PR includes version bump to v0.0.4
=> [From bot] Release master v0.0.4 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.5
=> [From bot] Release master v0.0.5 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.6
=> [From bot] Release master v0.0.6 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.7
=> [From bot] Release master v0.0.7 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.8
=> [From bot] Release master v0.0.8 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.9
=> [From bot] Release master v0.0.9 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.10
=> [From bot] Release master v0.0.10 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.11
=> [From bot] Release master v0.0.11 from production

CHANGELOG.md, package.json
This PR includes version bump to v0.0.12
=> [From bot] Release master v0.0.12 from production

.env, .github/workflows/build.yml, .github/workflows/create-release-PR.yml, .github/workflows/release.yml, .release-it.json, package.json, packages/bin/release-pr.js, packages/bin/release.js, packages/config/fe-scripts.json, packages/lib/releaseConfig.js, packages/lib/relesae.js, packages/utils/files.js
=> test: Feat/release setup

CHANGELOG.md, package.json
This PR includes version bump to test-v0.0.4
=> [Bot Release] Branch test, Tag: test-v0.0.4, Env: production

CHANGELOG.md, package.json
This PR includes version bump to test-v0.0.6
=> [Bot Release] Branch test, Tag: test-v0.0.6, Env: production

CHANGELOG.md, package.json
This PR includes version bump to test_v0.0.7
=> [Bot Release] Branch test, Tag: test_v0.0.7, Env: production

CHANGELOG.md, package.json
This PR includes version bump to test_v0.0.8
=> [Bot Release] Branch test, Tag: test_v0.0.8, Env: production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.13
=> [Bot Release] Branch master, Tag: 0.0.13, Env: production

CHANGELOG.md, package.json, packages/config/fe-scripts.json, packages/lib/releaseConfig.js
This PR includes version bump to 0.0.14
=> [Bot Release] Branch master, Tag: 0.0.14, Env: production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.15
=> [Bot Release] Branch:test, Tag:0.0.15, Env:production

CHANGELOG.md, package.json
This PR includes version bump to test_0.0.16
=> [Bot Release] Branch:test, Tag:test_0.0.16, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.16
=> [Bot Release] Branch:master, Tag:0.0.16, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.17
=> [Bot Release] Branch:master, Tag:0.0.17, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.18
=> [Bot Release] Branch:master, Tag:0.0.18, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.19
=> [Bot Release] Branch:master, Tag:0.0.19, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.20
=> [Bot Release] Branch:master, Tag:0.0.20, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.21
=> [Bot Release] Branch:master, Tag:0.0.21, Env:production

.github/workflows/release.yml, .github/workflows/update-version.yml, package.json
Reverts qlover/fe-base-scripts#62
=> Revert "Fix/ci pr lable skip update version"

CHANGELOG.md, package.json
This PR includes version bump to 0.0.22
=> [Bot Release] Branch:master, Tag:0.0.22, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.24
=> [Bot Release] Branch:master, Tag:0.0.24, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.25
=> [Bot Release] Branch:master, Tag:0.0.25, Env:production

CHANGELOG.md, package.json
This PR includes version bump to 0.0.26
=> [Bot Release] Branch:master, Tag:0.0.26, Env:production
